### ISSUE TITLE
In 2021 it's shocking to not be using HTTPS.

### ISSUE THREAD

**Issue by Athanasius** [gbiobob/EDCodex#35]
Lets Encrypt makes it super easy to get, use and renew a free SSL/HTTPS certificate.

You don't even have the shaky excuse of "but we don't do any authentication" as you have accounts.

Move out of the 2000s and into the 2010/2020s, encyrpt today!

**Comment by dylan-k** [comment]
I wonder how up-to-date this project is. The "last news" is from several years ago, the forums have spam, and several of the issues here on github have been open for 5 years. I wonder if there's a way the community could help make updates faster?

**Comment by gbiobob** [comment]
Yes no excuse :) switch to https is planned for a while. 
Not done yet because I don't have enough control over the current hosting to do it. I have planned to migrate to a new hosting where I have full control (provided for free by a contributor), the new server is ready since few months and the last thing to do is to make the migration (this year has been busy IRL at work and it was complicated to find the necessary time). I did not rush things so far because before the release of Odyssey the community wasn't very active. I'll could try to speed up things if the Odyssey release wake up players (not play a lot on my side recently, the game runs slowly since the update).

About moderating the content on edcodex, I can give moderators rights if anyone wants to help.

Regarding the future of the website, I will probably archive not so much used parts in order to focus on the essential,
the FAQ, for example mainly attracts spam and not so much used. 
If there is ideas, i'm open for discuss.

**Comment by Athanasius** [comment]
Good to hear you're still around and active!  I hear you on the lack of time thing.

IF you run into any issues with LetsEncrypt/cerbot I might be able to help.  I use it with Apache web servers and use scripting to move the certificate files into place (I request them on one VM and then they get deployed to a WWW-only VM).

From others' experience using the certbot hooks to auto-update nginx *can* run into issues with nginx then not noticing the changed files leading to "Certificate Expired" if there's no nginx reload/restart in time.  My Apache setups likely avoid this due to a potential nightly reload for log rotations anyway.

**Comment by gbiobob** [comment]
Yes I still here for maintenance when I found extra time, I will keep the projet alive as people continue to post new entries.

The new host is on Apache (at this time we are on nginx), I will let know if help needed with LetsEncrypt :) 
(it should be OK, already got someone to help me on that part)

**Comment by gbiobob** [comment]
HTTPS is live on edcodex
