### ISSUE TITLE
abandonded

### ISSUE THREAD

**Issue by nick-elms** [gbiobob/EDCodex#41]
Thinking this website/project is abandoned. nothing new on the announcements page for 5 years now, and starting to get spam/porn links added with no moderation despite reports. Shame as this website was super helpful

**Comment by Razwerkz** [comment]
Looks that way to me.  Just tried to create an account, only to never receive an activation email.  No button on the website to resend the email, so I reached out to their support inbox... which, according to the Gmail delivery subsystem, does not currently exist.

> The response from the remote server was:
550 5.1.1 <[issues@edcodex.info](mailto:issues@edcodex.info)>: Recipient address rejected: User unknown in virtual mailbox table

**Comment by gbiobob** [comment]
@Razwerkz Hello, I am still active in maintaining EDCodex, I don't know what happened with your registration, I have a few other gmail users who have registered successfully in the last few days BUT I saw that there were also a lot of gmail spam accounts that tried to register. It may have been a temporary block because too many accounts were created at the same time.

I have manually activated your account

**Comment by Razwerkz** [comment]
@gbiobob Ah, that's great news!  Thank you for your help.  I was able to log in successfully.
